/**
 * What each glyph means, in words (ui-motion.md §4.4): for the gallery and
 * a card Key. Kept apart from the path tables so the words never ship with a
 * glyph that only draws.
 */
import type { GlyphName } from "./index";

export const GLYPH_MEANS: Readonly<Record<GlyphName, string>> = {
  "stage.foundation": "Foundation, level 4",
  "stage.familiar": "Familiar, level 6",
  "stage.retained": "Retained, level 8",
  "stage.fluent": "Fluent, level 10",
  "stage.mastered": "Mastered, level 12",
  "stage.toward": "Toward a stage (keeps the rank)",
  "stage.part": "A stage, part n",
  "stage.track": "A track plan's stage",
  "rank.0": "Aim rank Initiate",
  "rank.1": "Aim rank Aspirant",
  "rank.2": "Aim rank Journeyman",
  "rank.3": "Aim rank Specialist",
  "rank.4": "Aim rank Expert",
  "rank.5": "Aim rank Virtuoso",
  "rank.6": "Aim rank Paragon",
  "quest.bring": "Bring cards up a level · tested by your reviews",
  "quest.add": "Add new cards · counted by the app",
  "quest.practice": "Practice sessions · from your ticks",
  "quest.step": "A step · you tick it",
  "quest.checkpoint": "A checkpoint or the exam · you log it",
  "ev.tested": "tested by your reviews",
  "ev.counted": "counted by the app",
  "ev.tick": "from your ticks",
  "ev.log": "you log it",
  "ev.estimate": "an estimate",
  "ev.measured": "measured at",
  "pv.suggest": "Gemini suggestion · not checked",
  "pv.kept": "Gemini's words · kept by you · not checked",
  "pv.pick": "Gemini's choice among the app's options",
  "pv.integrity": "What Gemini's reply held",
  "pv.app": "Written by the app",
  "pv.you": "You wrote this · yours",
  "pv.checked": "You checked this",
  "pv.syllabus": "Your syllabus line",
  "safe.health": "Not medical advice",
  "safe.strike": "avoid (over a session)",
  "safe.in": "can include",
  "safe.ask": "waiting on your answer",
  "m.quote": "from your words",
  "m.verbatim": "shown exactly as written",
  "m.policy": "the app's policy, not facts",
  "m.judge": "yours to judge",
  "m.nopay": "pays nothing",
  "m.clash": "may clash with your aim",
  "sess.easy": "Easy session",
  "sess.mobility": "Mobility session",
  "sess.technique": "Technique session",
  "sess.harder": "Harder session",
  "sess.longer": "Longer session",
  "sess.strength": "Strength session",
  "sess.full": "Full attempt",
  "sess.perf": "Performance check",
  "v.fits": "Fits",
  "v.tight": "Tight",
  "v.over": "Over",
  "v.imp": "Impossible",
  "v.fitted": "Fitted",
  "v.unv": "Unverified",
  "t.cal": "a date set by the app",
  "t.cal-moved": "the app's date moved",
  "t.pin": "your own date",
  "t.earliest": "earliest if every review passes",
  "t.span": "the review gap",
  "t.hourglass": "set by reviews",
  "pace.on": "on pace",
  "pace.behind": "behind",
  "m.link": "counts toward another quota",
  "m.builds": "builds on the previous stage",
  "m.lock": "still needs your check",
  "m.seal": "reached (counted)",
  "m.queue": "the share of the queue cleared",
  "m.pause": "pause an animation",
  "intensity.light": "Light",
  "intensity.steady": "Steady",
  "intensity.push": "Push",
  route: "the aim route",
  "route.weave": "drafting",
  "m.minus": "less",
  "m.down": "down",
  "m.info": "about this",
  flame: "the streak flame: unlit, lit, kept",
  // ── Revision 5, lane 9 (ui-motion.md §15.1: the "Means" column, exactly) ──
  "pv.web": "Gemini's name · Google linked sources to it",
  "pv.library": "Your Domain",
  "pv.libpick": "Gemini picked one of your Domains · not checked",
  "pv.named": "named by Gemini",
  "layer.1": "Layer 1 of the topic map",
  "layer.2": "Layer 2 of the topic map",
  "layer.3": "Layer 3 of the topic map",
  "layer.4": "Layer 4 of the topic map",
  "layer.5": "Layer 5 of the topic map",
  "layer.6": "Layer 6 of the topic map",
  "goal.1": "Goal 1",
  "goal.2": "Goal 2",
  "goal.3": "Goal 3",
  "goal.paused": "A paused goal",
};
